import { ArrowUpRight, Blocks, Check, Command, Cpu, ShieldCheck } from 'lucide-react'
import { Footer, Header, ProductCard, SectionLabel } from '@/components/site'
import { productCatalog } from '@/components/product-data'

const tools = [
  { title: 'Smart Contract Builder', text: 'Compose, test, and deploy contract logic through a clear, dependable development workflow.' },
  { title: 'Dapp Builder', text: 'Turn protocol capabilities into focused applications without rebuilding the same foundations.' },
  { title: 'Chain Observatory', text: 'Inspect network state, transactions, and system behavior through one operational view.' },
]

export default function Page() {
  return <main className="min-h-screen overflow-hidden bg-[#0b0d0c] text-white">
    <Header />
    <section className="relative mx-auto flex min-h-[560px] max-w-[1240px] items-end overflow-hidden px-6 pb-20 pt-12 lg:min-h-[640px] lg:px-8 lg:pb-24 lg:pt-14">
      <div className="pointer-events-none absolute inset-0 opacity-60 [background-image:linear-gradient(rgba(255,255,255,0.045)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.045)_1px,transparent_1px)] [background-size:72px_72px] [mask-image:linear-gradient(to_bottom,transparent,black_20%,black_68%,transparent)]" />
      <div className="pointer-events-none absolute -right-48 top-20 size-[580px] rounded-full bg-[#58e791]/[0.1] blur-[150px]" />
      <div className="pointer-events-none absolute bottom-[-26%] left-[35%] size-[420px] rounded-full bg-[#58e791]/[0.06] blur-[120px]" />
      <div className="relative max-w-4xl"><p className="mb-6 text-xs uppercase tracking-[0.28em] text-white/40">Infrastructure for a more useful blockchain</p><h1 className="max-w-4xl text-[clamp(3.5rem,9vw,8.5rem)] font-medium leading-[0.91] tracking-[-0.07em] text-white">Blockchain,<br /><span className="text-[#58e791]">made useful.</span></h1><div className="mt-10 flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><p className="max-w-md text-base leading-7 text-white/50">Hashed Solutions builds the infrastructure that turns blockchain capability into clear, dependable products people can use.</p><a href="#services" className="group flex w-fit items-center gap-3 text-sm text-white">Explore our work <span className="flex size-9 items-center justify-center rounded-full border border-white/20 transition-all group-hover:border-[#58e791] group-hover:bg-[#58e791] group-hover:text-[#0b0d0c]"><ArrowUpRight className="size-4" /></span></a></div></div>
    </section>
    <section id="services" className="border-y border-white/10 bg-[#101311]"><div className="mx-auto max-w-[1240px] px-6 py-28 lg:px-8 lg:py-36"><div className="mb-20 flex flex-col justify-between gap-8 sm:flex-row sm:items-end"><div><SectionLabel>Our services</SectionLabel><h2 className="text-4xl font-medium tracking-[-0.04em] sm:text-6xl">Systems with purpose.</h2></div><p className="max-w-xs text-sm leading-6 text-white/40">Focused infrastructure for teams moving value, state, and information across the decentralized web.</p></div><div className="grid gap-12 md:grid-cols-3 md:gap-8">{productCatalog.map((product) => <ProductCard key={product.slug} product={product} />)}</div></section>
    <section id="tools" className="mx-auto max-w-[1240px] px-6 py-28 lg:px-8 lg:py-36"><div className="mb-16 flex flex-col justify-between gap-8 sm:flex-row sm:items-end"><div><SectionLabel>Our tools</SectionLabel><h2 className="text-4xl font-medium tracking-[-0.04em] sm:text-6xl">Build from a stronger base.</h2></div><p className="max-w-xs text-sm leading-6 text-white/40">Practical tools that make complex blockchain work easier to design, ship, and operate.</p></div><div className="grid border-y border-white/10 md:grid-cols-3 md:divide-x md:divide-white/10">{tools.map((tool, index) => <div key={tool.title} className="border-b border-white/10 py-8 md:border-b-0 md:px-8 md:first:pl-0 md:last:pr-0"><span className="font-mono text-xs text-white/30">0{index + 1}</span><h3 className="mt-12 mb-3 text-lg font-medium text-white">{tool.title}</h3><p className="text-sm leading-6 text-white/40">{tool.text}</p></div>)}</div></section>
    <section id="technology" className="border-y border-white/10 bg-[#101311]"><div className="mx-auto grid max-w-[1240px] gap-16 px-6 py-32 lg:grid-cols-[0.8fr_1.2fr] lg:px-8 lg:py-40"><div><SectionLabel>The technology</SectionLabel><h2 className="max-w-md text-4xl font-medium leading-tight tracking-[-0.04em] sm:text-5xl">Designed for the layer between.</h2><p className="mt-8 max-w-sm text-sm leading-6 text-white/45">We work where protocol logic meets product reality—building infrastructure that is secure by design and calm to operate.</p></div><div className="grid gap-px overflow-hidden border border-white/10 bg-white/10 sm:grid-cols-2"><Tech icon={ShieldCheck} title="Protocol integrity" text="Native validation and clear state guarantees at every layer." /><Tech icon={Blocks} title="Composability" text="Modular systems that adapt to chains, teams, and use cases." /><Tech icon={Command} title="Human interfaces" text="Tools that make advanced blockchain capabilities approachable." /><Tech icon={Check} title="Operational clarity" text="Predictable behavior from first transaction to final settlement." /></div></div></section>
    <section id="about" className="mx-auto grid max-w-[1240px] gap-16 px-6 py-32 lg:grid-cols-[1fr_1.4fr] lg:px-8 lg:py-48"><div><SectionLabel>What we believe</SectionLabel><h2 className="max-w-md text-4xl font-medium leading-tight tracking-[-0.04em] text-white sm:text-5xl">Blockchain should feel less like infrastructure.</h2></div><div className="max-w-2xl space-y-7 text-lg leading-8 text-white/50"><p>We are building the connective tissue between blockchain primitives and the products people actually want to use.</p><p>Our work focuses on the hard edges: settlement, state, data, and developer experience. We turn protocol complexity into dependable systems that teams can build on with confidence.</p><p>The result is technology that respects the underlying networks—and makes them feel simple.</p></div></section>
    <section id="contact" className="relative border-t border-white/10"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(88,231,145,0.12),transparent_48%)]" /><div className="relative mx-auto max-w-[1240px] px-6 py-32 text-center lg:px-8 lg:py-44"><p className="mb-7 text-xs uppercase tracking-[0.24em] text-[#58e791]">Build with us</p><h2 className="mx-auto max-w-3xl text-5xl font-medium leading-[0.98] tracking-[-0.06em] sm:text-7xl">The next layer<br />starts here.</h2><a href="mailto:hello@hashedsolutions.com" className="mt-12 inline-flex items-center gap-3 rounded-full bg-[#58e791] px-6 py-3.5 text-sm font-medium text-[#0b0d0c] transition-transform hover:scale-[1.03]">Start a conversation <ArrowUpRight className="size-4" /></a></div></section>
    <Footer />
  </main>
}

function Tech({ icon: Icon, title, text }: { icon: typeof ShieldCheck; title: string; text: string }) { return <div className="bg-[#0b0d0c] p-7 sm:p-9"><Icon className="mb-14 size-5 text-[#58e791]" strokeWidth={1.4} /><h3 className="mb-3 text-base font-medium text-white">{title}</h3><p className="text-sm leading-6 text-white/40">{text}</p></div> }

export { Page }
