import Link from 'next/link'
import { ArrowLeft, ArrowUpRight, Check, Database, LockKeyhole, Network } from 'lucide-react'
import { Footer, Header, SectionLabel } from '@/components/site'
import { productCatalog } from '@/components/product-data'

export function generateStaticParams() { return productCatalog.map((product) => ({ slug: product.slug })) }

export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const product = productCatalog.find((item) => item.slug === slug) ?? productCatalog[0]
  const Icon = { mepp: LockKeyhole, acci: Network, data: Database }[product.slug]
  return <main className="min-h-screen bg-[#0b0d0c] text-white"><Header /><section className="mx-auto max-w-[1240px] px-6 pb-28 pt-40 lg:px-8 lg:pb-40"><Link href="/#products" className="mb-24 inline-flex items-center gap-2 text-xs uppercase tracking-[0.18em] text-white/40 transition-colors hover:text-[#58e791]"><ArrowLeft className="size-3.5" /> All products</Link><div className="grid gap-16 lg:grid-cols-[1.1fr_0.9fr] lg:gap-24"><div><div className="mb-8 flex items-center gap-4"><span className="flex size-12 items-center justify-center rounded-full border border-[#58e791]/40 text-[#58e791]"><Icon className="size-5" strokeWidth={1.3} /></span><span className="font-mono text-xs text-white/35">{product.code} / HAShed systems</span></div><h1 className="text-7xl font-medium tracking-[-0.07em] sm:text-9xl">{product.name}</h1><p className="mt-8 max-w-xl text-xl leading-8 text-white/50">{product.label}. {product.description}</p></div><div className="flex items-end"><div className="border-l border-[#58e791] pl-6"><p className="text-xs uppercase tracking-[0.2em] text-[#58e791]">Product brief</p><p className="mt-5 text-base leading-7 text-white/65">{product.detail}</p></div></div></div></section><section className="border-y border-white/10 bg-[#101311]"><div className="mx-auto grid max-w-[1240px] gap-14 px-6 py-28 lg:grid-cols-[0.8fr_1.2fr] lg:px-8"><div><SectionLabel>Capabilities</SectionLabel><h2 className="text-3xl font-medium tracking-tight">Built to remove friction.</h2></div><div className="grid gap-5 sm:grid-cols-3">{product.features.map((feature) => <div key={feature} className="border-t border-white/15 pt-5"><Check className="mb-8 size-4 text-[#58e791]" strokeWidth={1.5} /><p className="text-sm leading-6 text-white/60">{feature}</p></div>)}</div></div></section><section className="mx-auto max-w-[1240px] px-6 py-28 lg:px-8"><div className="flex flex-col items-start justify-between gap-8 sm:flex-row sm:items-center"><div><p className="text-sm text-white/40">Have a use case in mind?</p><h2 className="mt-2 text-3xl font-medium tracking-tight">Let&apos;s build the right layer.</h2></div><a href="mailto:hello@hashedsolutions.com" className="inline-flex items-center gap-3 rounded-full bg-[#58e791] px-6 py-3.5 text-sm font-medium text-[#0b0d0c]">Talk to our team <ArrowUpRight className="size-4" /></a></div></section><Footer /></main>
}
